config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  get 'static_pages/about'

  devise_for :users
	
  resources :contacts
  resources :categories
  resources :buyers
  resources :sellers
  resources :properties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root to: 'properties#index'
end

app/models/property.rb
class Property < ApplicationRecord
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user! , except: [:index,:show]
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:property_id, :name, :category_id, :buyer_id, :seller_id, :price, :location, :description)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :property_id %>
    <%= form.number_field :property_id, id: :property_property_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :property_name %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.number_field :category_id, id: :property_category_id %>
  </div>

  <div class="field">
    <%= form.label :buyer_id %>
    <%= form.number_field :buyer_id, id: :property_buyer_id %>
  </div>

  <div class="field">
    <%= form.label :seller_id %>
    <%= form.number_field :seller_id, id: :property_seller_id %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :property_price %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :property_location %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :property_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

        
            <div class="col-md-3">
                <p class="lead">Categories</p>
                <div class="list-group">
                    <a href="#" class="list-group-item">Buy</a>
                    <a href="#" class="list-group-item">Sell</a>
                    <a href="#" class="list-group-item">Rent/Lease</a>
                </div>
            </div>

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="http://placehold.it/320x150" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/320x150" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/320x150" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>

                </div>

                <div class="row">

                    <% @properties.each do |property| %> 
                        <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="http://placehold.it/320x150" width="320" height="150" alt="">
                            <div class="caption">
                                <h4 class="pull-right"><p><%= property.price %></p> </h4>
                                <h4><%= link_to property.name , property_path(property.id) %>
                                </h4>
                                <p></p>
                            </div>
                            
                          </div>
                       
                    </div>
                    <% end %>

                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <h4><a href="#">View More</a>
                        </h4>
                        
                    </div>

                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->

<% if user_signed_in? %>
<%= link_to 'New Property', new_property_path %>
<% end %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<div class="about-top" id="about">
  <div class="container">
    
    <div class="wthree-services-bottom-grids">
      <div class="col-md-6 wthree-services-left">
        <img src="http://placehold.it/900x300" alt="">
      </div>
      <div class="col-md-6 wthree-services-right first-w3l">
        <div class="wthree-services-right-top">
          <h4>Property Description</h4>
          <p> <%= @property.name %></p>
          <p><%= @property.price %></p>
          <p><%= @property.location %></p>
          <p><%= @property.description %></p>
          
        </div>
        <div class="wthree-services-right-bottom">
          <div class="services-right-bottom-bottom">
            <div class="col-xs-1 services-bottom-icon">
              <i class="fa fa-home" aria-hidden="true"></i>
            </div>
            <div class="col-xs-11 services-bottom-info">
              <h5></h5>
              <p></p>
            </div>
            <div class="clearfix"> </div>
          </div>
          <div class="services-right-bottom-bottom">
            <div class="col-xs-1 services-bottom-icon">
              <i class="fa fa-key" aria-hidden="true"></i>
            </div>
            <div class="col-xs-11 services-bottom-info">
              <h5></h5>
              <p></p>
            </div>
            <div class="clearfix"> </div>
          </div>
        </div>
        <div class="clearfix"> </div>
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>
</div>
<% @contact = Contact.new %>
<%= form_for(@contact) do |form| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this registration from being saved:</h2>
      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h3>Fill the form to contact the owner</h3>
   <%= form.hidden_field :property_id, value: @property.id %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message,class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Enter", class: "btn btn-primary" %>
  </div>
  <% end %>
   


<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>